### PR TITLE
Updated the GbmSaa class to include the new SAA polygon

### PR DESCRIPTION
**Pull request by joshuarwood**
This pull request makes the following changes:
1. Updates the GbmSAA class to allow for time-dependent handling of the SAA polygon. This allows users to switch between using the original SAA polygon versus the new one depending on the time they are analyzing. A time is now passed when initializing GbmSaa objects. Existing objects can be updated to new times with the `update()` method.
2. Updated `tests/missions/fermi/gbm/test_saa.py` to test both new & old SAA polygons.
3. Updated saa documentation to describe the changes + include a comparison of new & old SAA polygons.

### CODE REVIEW

**Comment by AdamGoldstein-USRA** [comment]
For backwards compatibility and simplicity for the user, it would be better to have the `time` argument in the constructor be an optional kwarg.  If the optional kwarg is not set, it retrieves the current SAA boundary.

**Comment by joshuarwood** [comment]
Some additional comments after chatting with Adam:
   * we probably want to define individual SAA regions as immutable classes
   * have the GbmSaa class select which polygon it needs based on a time range. Time range will be start until present if only one region is given.
   * make sure the GbmSaa class chooses the most recent region via a default kwarg
  
  We can debut this in gdt-fermi and then eventually make it a gdt-core behavior.

**Comment by BillCleveland-USRA** [comment]
Do you still want to this PR to reviewed, or are you still discussing the changes?  If there are some significant changes to be done, then maybe we cancel this PR and resubmit when the modifications are done.

**Comment by joshuarwood** [comment]
I have one more change to add a sanity check to ensure the GbmSaaCollection doesn't include polygons that overlap in time. I think I can prepare that and update the unit tests/docs by tomorrow (Friday 8/2).

**Comment by joshuarwood** [comment]
Ok, SAA polygons are now sorted and checked for time range overlaps when initializing GbmSaaCollection. I updated the unit tests and docs. I believe this is ready for final review.

**Comment by joshuarwood** [comment]
Caught a few remaining things that needed to be unit tested. Test coverage is now 100%. Ok, now it's done...

**Review by AdamGoldstein-USRA — APPROVED** [review]

**Pull request merged**
